# Finding the most important characteristics of the clients

In [1]:
import pandas as pd 
import numpy as np

## Cleaning and wrangling of data

In [2]:
pd.set_option('display.max_columns', 100)

In [3]:
data = pd.read_csv("clientes_startup_summer.csv")

In [4]:
data

,ID,Nombre_Alumnos,Genero_Alumno,Edad,Grupo,Nombre_Tutor,Genero_Tutor,Paquete,Semanas,Colonia,Municipio,C.P.,Escuela,Hermanos,Compra
0,1,Fernando Vargas Rodriguez,Masculino,4.0,1.0,Vania Rodriguez,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
1,2,Ivan Rasid,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
2,3,Miguel Ángel Vargas,Masculino,12.0,3.0,Guillermina López,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,1,Si
3,4,Ian Montoya Tenorio,Masculino,8.0,1.0,Miriam Tenorio Rico,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
4,5,Maria Palomino,Femenino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
5,6,Andrei Quetzal López,Masculino,NaN,NaN,NaN,NaN,Alimento,3.0,NaN,NaN,NaN,NaN,0,No
6,7,Sayed Charbel,Masculino,14.0,3.0,Carlos Galdoz Bustamante,Masculino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
7,8,Andrea Zuleta Malanco,Femenino,12.0,3.0,Diana Malanco Villena,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,0,Si
8,9,Jorge Ochoa Arteaga,Masculino,13.0,3.0,Iris Arteaga,Femenino,Normal,2.0,NaN,Aguascalientes,NaN,NaN,3,Si
9,10,Rogelio Ortega Hernández,Masculino,7.0,1.0,Rogelio Ortega Padilla,Masculino,Alimento,3.0,NaN,NaN,NaN,NaN,0,Si
10,11,Amelie Espinoza Viscencio,Femenino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
11,12,Emiliano Santillan,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
12,13,Santiago Ortiz Corzo,Masculino,7.0,1.0,Omar Ulisis Ortiz Jaramillo,Masculino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
13,14,Natalia Diaz Naa,Femenino,NaN,NaN,NaN,NaN,Alimento,3.0,NaN,NaN,NaN,NaN,0,No
14,15,Yair Diaz Pardo,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
15,16,Juan Solis Jiménez,Masculino,5.0,1.0,Giovani Solis,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,2,Si
16,17,Ivan Solis Jiménez,Masculino,7.0,1.0,Giovani Solis,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,2,Si
17,18,Giovani Solis Jiménez,Femenino,8.0,1.0,Giovani Solis,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,2,Si
18,19,Gilberto Salado,Masculino,11.0,2.0,Gilberto Salado,Masculino,Alimento,3.0,NaN,NaN,NaN,NaN,0,Si
19,20,Fernando Galicia Garcia,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
20,21,Luis Murillo de León,Masculino,7.0,1.0,Elizabeth de Leon Gallo,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
21,22,Enrique Barba Montañez,Masculino,8.0,1.0,Enrique Barba López,Masculino,Alimento,3.0,NaN,Aguascalientes,20080.0,NaN,0,Si
22,23,Nestor Dominguez López,Masculino,9.0,2.0,Nestor Dominguez López,Masculino,Normal,3.0,NaN,San_Pedro_Garza_García,66269.0,NaN,0,Si
23,24,Natalia Olguin Gutierrez,Femenino,13.0,3.0,Selene Gutierrez Mier,Femenino,Normal,3.0,Jardines de la Concepción,Aguascalientes,20120.0,NaN,1,Si
24,25,Cristina Olguin Gutierrez,Femenino,10.0,2.0,Selene Gutierrez Mier,Femenino,Normal,3.0,Jardines de la Concepción,Aguascalientes,20120.0,NaN,1,Si
25,26,Vidal De Anda Pizaña,Masculino,8.0,1.0,Wendy Pizaña Hurtado,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
26,27,Alejandro Varela Moreno,Masculino,10.0,2.0,Claudia Moreno,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
27,28,Jesus León Espinoza,Masculino,7.0,1.0,Victor Leon,Masculino,Alimento,3.0,NaN,NaN,NaN,Entorno,0,Si
28,29,Carlos Herrera Estrada,Masculino,8.0,1.0,Carlos Herrera Navarro,Masculino,Normal,3.0,NaN,jesus María,2098.0,Entorno,0,Si
29,30,Regina Lucci Garcés,Femenino,13.0,3.0,Mercedes Garcés,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,0,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,119,Emilio Riverón,Masculino,11.0,2.0,Norma Gabriela,Femenino,Alimento,2.0,Jardines de la Concepción,Aguascalientes,20120.0,NaN,0,Si
117,120,Sara Guerra Macias,Femenino,12.0,3.0,Juan Eduardo González,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,2,Si
118,121,César Said Morán,Masculino,7.0,1.0,Fabiola Guzmán,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
119,122,Pablo Samaniego Osuna,Masculino,13.0,3.0,Eduardo Samaniego Hernández,Masculino,Normal,1.0,NaN,NaN,NaN,NaN,0,Si
120,123,Alejandro Romo Cedillo,Masculino,14.0,3.0,Jorge Romo Rojas,Masculino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
121,124,José Medina Romo,Masculino,13.0,3.0,Norma Romo,Femenino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
122,125,Saul Monroy Ramos,Masculino,10.0,2.0,Laura Ramos,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,0,Si
123,126,Alexa Tadanga García,Femenino,8.0,1.0,Alyn Garcia Chi,Femenino,Normal,1.0,NaN,NaN,NaN,NaN,0,Si
124,127,Emiliano Martinez Flores,Masculino,11.0,2.0,Juana Flores Jiménez,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,0,Si
125,128,Itzara Luévano del Río,Femenino,NaN,NaN,NaN,NaN,Normal,2.0,NaN,NaN,NaN,NaN,0,No
126,129,Santiago Flores de Lara,Masculino,NaN,NaN,NaN,NaN,Normal,1.0,NaN,NaN,NaN,NaN,0,No
127,130,Maria González Macias,Femenino,12.0,3.0,Juan González González,Masculino,Normal,3.0,NaN,NaN,NaN,NaN,2,SI
128,132,Ana González Macias,Femenino,8.0,1.0,Juan Eduardo González,Masculino,Normal,3.0,NaN,NaN,NaN,NaN,2,SI
129,133,Luis Varona Gutierrez,Masculino,8.0,1.0,Hilda Gutierrez,Femenino,NaN,NaN,NaN,NaN,NaN,NaN,0,SI
130,134,Natalia Penna Rodriguez,Femenino,8.0,1.0,Cecilia Rodriguez,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,1,SI
131,135,Santiafo Penna Rodriguez,Masculino,11.0,2.0,Cecilia Rodriguez,Femenino,Alimento,3.0,NaN,NaN,NaN,NaN,1,SI
132,136,Sebastian Gutierrez Limon,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
133,137,Fernando Gutierrez Limon,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,1,No
134,138,Christian Sánchez Rodriguez,Masculino,13.0,3.0,Rodrigo Urueña,Masculino,Normal,3.0,NaN,NaN,NaN,NaN,0,Si
135,139,Alan Cortes Harrup,Masculino,NaN,NaN,NaN,NaN,Alimento,1.0,NaN,NaN,NaN,NaN,0,No
136,140,Gerardo Barba Ruiz,Masculino,NaN,NaN,NaN,NaN,Normal,1.0,NaN,NaN,NaN,NaN,0,No
137,141,Diego Garza Sola,Masculino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,1,No
138,142,Adair Lara Martinez,Masculino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,No
139,143,Karim Gutierrez Estrada,Femenino,NaN,NaN,NaN,NaN,Alimento,2.0,NaN,NaN,NaN,NaN,0,No
140,144,Danna Berrones Espino,Femenino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,0,No
141,146,Romina Marcos Vega,Femenino,NaN,NaN,NaN,NaN,Normal,2.0,NaN,NaN,NaN,NaN,2,No
142,147,Fernanda Marcos Vegas,Femenino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,2,No
143,148,Yeli Marcos Vega,Femenino,NaN,NaN,NaN,NaN,Normal,3.0,NaN,NaN,NaN,NaN,2,No
144,149,Florencia Alcala Lomelí,Femenino,NaN,NaN,NaN,NaN,Normal,1.0,NaN,NaN,NaN,NaN,0,No
145,150,Liliana Rodriguez,Femenino,NaN,NaN,NaN,NaN,Normal,1.0,NaN,NaN,NaN,NaN,1,No

In [5]:
data.shape

(146, 15)

In [7]:
data_nombres = data #To make a list with the tutors that pay for more than one child

In [8]:
drop_variables = ["ID", "Nombre_Alumnos", "Nombre_Tutor", "Colonia", "C.P."]
#The ID is insignificant 
#The names are no necessary for a ranking
#"Colonia" and "C.P." don't have eneough data to be useful in the analysis

In [9]:
data.drop(labels=drop_variables, axis=1, inplace=True)

In [10]:
data.head()

,Genero_Alumno,Edad,Grupo,Genero_Tutor,Paquete,Semanas,Municipio,Escuela,Hermanos,Compra
0,Masculino,4.0,1.0,Femenino,Normal,3.0,NaN,NaN,0,Si
1,Masculino,NaN,NaN,NaN,Normal,3.0,NaN,NaN,0,No
2,Masculino,12.0,3.0,Femenino,Alimento,3.0,NaN,NaN,1,Si
3,Masculino,8.0,1.0,Femenino,Normal,3.0,NaN,NaN,0,Si
4,Femenino,NaN,NaN,NaN,Normal,3.0,NaN,NaN,0,No

In [11]:
data.shape

(146, 10)

In [12]:
d_type = np.NAN
for column in data.columns:
    if data[column].dtype == np.int64:
        d_type = 'intenger'
    elif data[column].dtype == np.float64:
        d_type = 'float'
    else:
        d_type = 'other'
                
    print('VARIABLE: ', column)
    print('Type: ', d_type)
    print('NUNIQUE: ', data[column].nunique())
    print('UNIQUE: ', data[column].unique())
    print('VALUE COUNTS ', data[column].value_counts().head())
    print('\n')

VARIABLE:  Genero_Alumno
Type:  other
NUNIQUE:  2
UNIQUE:  ['Masculino' 'Femenino']
VALUE COUNTS  Masculino    97
Femenino     49
Name: Genero_Alumno, dtype: int64


VARIABLE:  Edad
Type:  float
NUNIQUE:  11
UNIQUE:  [ 4. nan 12.  8. 14. 13.  7.  5. 11.  9. 10.  6.]
VALUE COUNTS  8.0     19
10.0    14
11.0    12
7.0     12
13.0    11
Name: Edad, dtype: int64


VARIABLE:  Grupo
Type:  float
NUNIQUE:  3
UNIQUE:  [ 1. nan  3.  2.]
VALUE COUNTS  1.0    37
2.0    36
3.0    24
Name: Grupo, dtype: int64


VARIABLE:  Genero_Tutor
Type:  other
NUNIQUE:  2
UNIQUE:  ['Femenino' nan 'Masculino']
VALUE COUNTS  Femenino     69
Masculino    31
Name: Genero_Tutor, dtype: int64


VARIABLE:  Paquete
Type:  other
NUNIQUE:  2
UNIQUE:  ['Normal' 'Alimento' nan]
VALUE COUNTS  Normal      87
Alimento    57
Name: Paquete , dtype: int64


VARIABLE:  Semanas
Type:  float
NUNIQUE:  3
UNIQUE:  [ 3.  2.  1. nan]
VALUE COUNTS  3.0    103
1.0     29
2.0     12
Name: Semanas, dtype: int64


VARIABLE:  Municipio
Type:  other
NUNIQUE:  5
UNIQUE:  [nan 'Aguascalientes' 'San_Pedro_Garza_García' 'jesus María' 'Morelia'
 'Jesus María']
VALUE COUNTS  Aguascalientes            17
Morelia                    2
jesus María                1
Jesus María                1
San_Pedro_Garza_García     1
Name: Municipio, dtype: int64


VARIABLE:  Escuela
Type:  other
NUNIQUE:  2
UNIQUE:  [nan 'Entorno' 'Nuevos Horizontes']
VALUE COUNTS  Entorno              11
Nuevos Horizontes     1
Name: Escuela , dtype: int64


VARIABLE:  Hermanos
Type:  intenger
NUNIQUE:  4
UNIQUE:  [0 1 3 2]
VALUE COUNTS  0    80
1    41
2    21
3     4
Name: Hermanos, dtype: int64


VARIABLE:  Compra
Type:  other
NUNIQUE:  3
UNIQUE:  ['Si' 'No' 'SI']
VALUE COUNTS  Si    103
No     38
SI      5
Name: Compra , dtype: int64

### Dealing with nan's

In [13]:
#Changing the names of the columns due to a space in their name
data = data.rename(columns={'Paquete ': 'Paquete', 'Compra ': 'Compra',
                            'Escuela ': 'Escuela'
                           })

In [14]:
data["Genero_Tutor"] = data["Genero_Tutor"].fillna("Desconocido")
data["Municipio"] = data["Municipio"].fillna("Desconocido")
data["Paquete"] = data["Paquete"].fillna("Desconocido")
data["Escuela"] = data["Escuela"].fillna("Desconocido")

In [15]:
data["Semanas"] = data["Semanas"].fillna(data["Semanas"].mean())
data["Edad"] = data["Edad"].fillna(data["Edad"].mean())
data["Grupo"] = data["Grupo"].fillna(data["Grupo"].mean())

In [16]:
data.head()

,Genero_Alumno,Edad,Grupo,Genero_Tutor,Paquete,Semanas,Municipio,Escuela,Hermanos,Compra
0,Masculino,4.000000,1.000000,Femenino,Normal,3.0,Desconocido,Desconocido,0,Si
1,Masculino,9.690722,1.865979,Desconocido,Normal,3.0,Desconocido,Desconocido,0,No
2,Masculino,12.000000,3.000000,Femenino,Alimento,3.0,Desconocido,Desconocido,1,Si
3,Masculino,8.000000,1.000000,Femenino,Normal,3.0,Desconocido,Desconocido,0,Si
4,Femenino,9.690722,1.865979,Desconocido,Normal,3.0,Desconocido,Desconocido,0,No

### Modifying values within a column

In [17]:
data["Compra"].unique()

array(['Si', 'No', 'SI'], dtype=object)

In [18]:
dicc_state = {'SI':"Si"}

In [19]:
data.Compra.replace(dicc_state, inplace=True)

In [20]:
data["Compra"].unique()

array(['Si', 'No'], dtype=object)

In [21]:
data.columns.values

array(['Genero_Alumno', 'Edad', 'Grupo', 'Genero_Tutor', 'Paquete',
       'Semanas', 'Municipio', 'Escuela', 'Hermanos', 'Compra'],
      dtype=object)

In [22]:
data

,Genero_Alumno,Edad,Grupo,Genero_Tutor,Paquete,Semanas,Municipio,Escuela,Hermanos,Compra
0,Masculino,4.000000,1.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
1,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
2,Masculino,12.000000,3.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,1,Si
3,Masculino,8.000000,1.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
4,Femenino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
5,Masculino,9.690722,1.865979,Desconocido,Alimento,3.000000,Desconocido,Desconocido,0,No
6,Masculino,14.000000,3.000000,Masculino,Normal,3.000000,Desconocido,Desconocido,0,Si
7,Femenino,12.000000,3.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,0,Si
8,Masculino,13.000000,3.000000,Femenino,Normal,2.000000,Aguascalientes,Desconocido,3,Si
9,Masculino,7.000000,1.000000,Masculino,Alimento,3.000000,Desconocido,Desconocido,0,Si
10,Femenino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
11,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
12,Masculino,7.000000,1.000000,Masculino,Normal,3.000000,Desconocido,Desconocido,0,Si
13,Femenino,9.690722,1.865979,Desconocido,Alimento,3.000000,Desconocido,Desconocido,0,No
14,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
15,Masculino,5.000000,1.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,2,Si
16,Masculino,7.000000,1.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,2,Si
17,Femenino,8.000000,1.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,2,Si
18,Masculino,11.000000,2.000000,Masculino,Alimento,3.000000,Desconocido,Desconocido,0,Si
19,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
20,Masculino,7.000000,1.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
21,Masculino,8.000000,1.000000,Masculino,Alimento,3.000000,Aguascalientes,Desconocido,0,Si
22,Masculino,9.000000,2.000000,Masculino,Normal,3.000000,San_Pedro_Garza_García,Desconocido,0,Si
23,Femenino,13.000000,3.000000,Femenino,Normal,3.000000,Aguascalientes,Desconocido,1,Si
24,Femenino,10.000000,2.000000,Femenino,Normal,3.000000,Aguascalientes,Desconocido,1,Si
25,Masculino,8.000000,1.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
26,Masculino,10.000000,2.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
27,Masculino,7.000000,1.000000,Masculino,Alimento,3.000000,Desconocido,Entorno,0,Si
28,Masculino,8.000000,1.000000,Masculino,Normal,3.000000,jesus María,Entorno,0,Si
29,Femenino,13.000000,3.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,0,Si
...,...,...,...,...,...,...,...,...,...,...
116,Masculino,11.000000,2.000000,Femenino,Alimento,2.000000,Aguascalientes,Desconocido,0,Si
117,Femenino,12.000000,3.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,2,Si
118,Masculino,7.000000,1.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
119,Masculino,13.000000,3.000000,Masculino,Normal,1.000000,Desconocido,Desconocido,0,Si
120,Masculino,14.000000,3.000000,Masculino,Normal,3.000000,Desconocido,Desconocido,0,Si
121,Masculino,13.000000,3.000000,Femenino,Normal,3.000000,Desconocido,Desconocido,0,Si
122,Masculino,10.000000,2.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,0,Si
123,Femenino,8.000000,1.000000,Femenino,Normal,1.000000,Desconocido,Desconocido,0,Si
124,Masculino,11.000000,2.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,0,Si
125,Femenino,9.690722,1.865979,Desconocido,Normal,2.000000,Desconocido,Desconocido,0,No
126,Masculino,9.690722,1.865979,Desconocido,Normal,1.000000,Desconocido,Desconocido,0,No
127,Femenino,12.000000,3.000000,Masculino,Normal,3.000000,Desconocido,Desconocido,2,Si
128,Femenino,8.000000,1.000000,Masculino,Normal,3.000000,Desconocido,Desconocido,2,Si
129,Masculino,8.000000,1.000000,Femenino,Desconocido,2.513889,Desconocido,Desconocido,0,Si
130,Femenino,8.000000,1.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,1,Si
131,Masculino,11.000000,2.000000,Femenino,Alimento,3.000000,Desconocido,Desconocido,1,Si
132,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
133,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,1,No
134,Masculino,13.000000,3.000000,Masculino,Normal,3.000000,Desconocido,Desconocido,0,Si
135,Masculino,9.690722,1.865979,Desconocido,Alimento,1.000000,Desconocido,Desconocido,0,No
136,Masculino,9.690722,1.865979,Desconocido,Normal,1.000000,Desconocido,Desconocido,0,No
137,Masculino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,1,No
138,Masculino,9.690722,1.865979,Desconocido,Desconocido,2.513889,Desconocido,Desconocido,0,No
139,Femenino,9.690722,1.865979,Desconocido,Alimento,2.000000,Desconocido,Desconocido,0,No
140,Femenino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,0,No
141,Femenino,9.690722,1.865979,Desconocido,Normal,2.000000,Desconocido,Desconocido,2,No
142,Femenino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,2,No
143,Femenino,9.690722,1.865979,Desconocido,Normal,3.000000,Desconocido,Desconocido,2,No
144,Femenino,9.690722,1.865979,Desconocido,Normal,1.000000,Desconocido,Desconocido,0,No
145,Femenino,9.690722,1.865979,Desconocido,Normal,1.000000,Desconocido,Desconocido,1,No

In [23]:
def createDummies(data,var_name):
    dummy = pd.get_dummies(data[var_name], prefix=var_name)
    data = data.drop(var_name, axis = 1)
    data = pd.concat([data, dummy ], axis = 1)
    return data

In [24]:
data = createDummies(data, "Genero_Alumno")
data = createDummies(data,"Paquete")
data = createDummies(data, "Genero_Tutor")
data = createDummies(data, "Municipio")
data = createDummies(data, "Escuela")

In [25]:
data.head()

,Edad,Grupo,Semanas,Hermanos,Compra,Genero_Alumno_Femenino,Genero_Alumno_Masculino,Paquete_Alimento,Paquete_Desconocido,Paquete_Normal,Genero_Tutor_Desconocido,Genero_Tutor_Femenino,Genero_Tutor_Masculino,Municipio_Aguascalientes,Municipio_Desconocido,Municipio_Jesus María,Municipio_Morelia,Municipio_San_Pedro_Garza_García,Municipio_jesus María,Escuela_Desconocido,Escuela_Entorno,Escuela_Nuevos Horizontes
0,4.000000,1.000000,3.0,0,Si,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0
1,9.690722,1.865979,3.0,0,No,0,1,0,0,1,1,0,0,0,1,0,0,0,0,1,0,0
2,12.000000,3.000000,3.0,1,Si,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0
3,8.000000,1.000000,3.0,0,Si,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0
4,9.690722,1.865979,3.0,0,No,1,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,0

In [28]:
Path = "/Users/andres/Documents/Universidad/Segundo_Semestre_ISC/Ingenieria_de_Software/Proyecto/"

In [31]:
data.to_csv(Path + "Clientes_limpio.csv", index=False)